name: Auto Merge Development into Main

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  merge-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.pusher.email }}"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout main 1
        run: |
          git checkout main
          git pull --rebase=false origin --prune --verbose

      - name: Checkout development
        run: |
          git checkout development
          git pull --rebase=false origin --prune --verbose

      - name: Checkout development 2
        run: |
          git checkout development
          git pull origin development

      - name: Merge main into development
        run: git merge main

      - name: Commit
        run: git commit

      - name: Push
        run: git push origin development
