name: Auto Merge Development into Main

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  merge-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.pusher.email }}"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout main
        run: git checkout main

      - name: Checkout development
        run: git checkout development

      - name: Merge main into development
        run: git merge main

      - name: Push changes to development
        run: git push origin development
